# Generated by Django 3.1.7 on 2021-03-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210228_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'ordering': ['-is_main_image']},
        ),
        migrations.AddField(
            model_name='productpicture',
            name='is_main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.design'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.producttype'),
        ),
    ]
