# Generated by Django 3.1.7 on 2021-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210301_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='show_in_menu',
            field=models.BooleanField(default=False),
        ),
    ]
