# Generated by Django 3.1.7 on 2021-03-02 21:54

from django.db import migrations
import easy_thumbnails.fields
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210301_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpicture',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(unique=True, upload_to=shop.models.make_filepath),
        ),
    ]
