# Generated by Django 3.1.6 on 2021-02-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('botdata', '0029_discordguild_channel_disabled_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('uses', models.IntegerField(default=0)),
                ('revisions', models.IntegerField(default=0)),
                ('official', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=90)),
                ('content', models.TextField()),
                ('owners', models.ManyToManyField(related_name='tags', to='botdata.DiscordUser')),
            ],
        ),
        migrations.CreateModel(
            name='TagAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=90)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_aliases', to='botdata.discorduser')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='tags.tags')),
            ],
        ),
    ]
