# Generated by Django 3.1.6 on 2021-02-20 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0029_discordguild_channel_disabled_message'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameModel(
            old_name='TagAliases',
            new_name='TagAlias',
        ),
    ]
