# Generated by Django 3.1.6 on 2021-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20210220_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=90, unique=True),
        ),
        migrations.AlterField(
            model_name='tagalias',
            name='name',
            field=models.CharField(db_index=True, max_length=90, unique=True),
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
        migrations.AlterModelTable(
            name='tagalias',
            table='tagalias',
        ),
    ]
