# Generated by Django 3.1.7 on 2021-02-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0001_squashed_0029_discordguild_channel_disabled_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discordguild',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
