# Generated by Django 3.1.4 on 2020-12-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channels',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guilds',
            options={},
        ),
        migrations.AlterModelOptions(
            name='members',
            options={},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
