# Generated by Django 3.1.4 on 2020-12-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0002_auto_20201212_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.guilds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='guild',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.guilds'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.channels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.members'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='weapon_sabotaged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='botdata.players'),
        ),
    ]
