# Generated by Django 3.1.7 on 2021-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0002_auto_20210228_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='opened_support_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
