# Generated by Django 3.1.4 on 2020-12-12 19:25

import botdata.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0003_auto_20201212_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('discord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('webhook_urls', models.JSONField(blank=True, default=[])),
                ('api_key', models.UUIDField(blank=True, null=True)),
                ('use_webhooks', models.BooleanField(default=True)),
                ('use_emojis', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=False)),
                ('allow_global_items', models.BooleanField(default=True)),
                ('tax_on_user_send', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mentions_when_killed', models.BooleanField(default=True)),
                ('show_duck_lives', models.BooleanField(default=True)),
                ('kill_on_miss_chance', models.SmallIntegerField(default=3)),
                ('duck_frighten_chance', models.SmallIntegerField(default=7)),
                ('clover_min_experience', models.SmallIntegerField(default=1)),
                ('clover_max_experience', models.SmallIntegerField(default=10)),
                ('base_duck_exp', models.SmallIntegerField(default=10)),
                ('per_life_exp', models.SmallIntegerField(default=7)),
                ('ducks_per_day', models.SmallIntegerField(default=96)),
                ('night_start_at', models.IntegerField(default=0)),
                ('night_end_at', models.IntegerField(default=0)),
                ('spawn_weight_normal_ducks', models.SmallIntegerField(default=100)),
                ('spawn_weight_super_ducks', models.SmallIntegerField(default=15)),
                ('spawn_weight_baby_ducks', models.SmallIntegerField(default=7)),
                ('spawn_weight_prof_ducks', models.SmallIntegerField(default=10)),
                ('spawn_weight_ghost_ducks', models.SmallIntegerField(default=1)),
                ('spawn_weight_moad_ducks', models.SmallIntegerField(default=5)),
                ('spawn_weight_mechanical_ducks', models.SmallIntegerField(default=1)),
                ('spawn_weight_armored_ducks', models.SmallIntegerField(default=3)),
                ('spawn_weight_golden_ducks', models.SmallIntegerField(default=1)),
                ('spawn_weight_plastic_ducks', models.SmallIntegerField(default=6)),
                ('spawn_weight_kamikaze_ducks', models.SmallIntegerField(default=6)),
                ('spawn_weight_night_ducks', models.SmallIntegerField(default=100)),
                ('spawn_weight_sleeping_ducks', models.SmallIntegerField(default=5)),
                ('ducks_time_to_live', models.SmallIntegerField(default=660)),
                ('super_ducks_min_life', models.SmallIntegerField(default=2)),
                ('super_ducks_max_life', models.SmallIntegerField(default=7)),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='DiscordGuild',
            fields=[
                ('discord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('vip', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=6)),
            ],
            options={
                'db_table': 'guilds',
            },
        ),
        migrations.CreateModel(
            name='DiscordMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', django_enumfield.db.fields.EnumField(default=50, enum=botdata.models.AccessLevel)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discordguild')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('discord_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('discriminator', models.CharField(max_length=4)),
                ('times_ran_example_command', models.IntegerField(default=0)),
                ('inventory', models.JSONField(blank=True, default=[])),
                ('trophys', models.JSONField(blank=True, default={})),
                ('ping_friendly', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=6)),
                ('first_use', models.BooleanField(default=True)),
                ('access_level_override', django_enumfield.db.fields.EnumField(default=50, enum=botdata.models.AccessLevel)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestige', models.SmallIntegerField(default=8)),
                ('prestige_last_daily', models.DateTimeField(auto_now_add=True)),
                ('prestige_dailies', models.IntegerField(default=0)),
                ('active_powerups', botdata.models.DefaultDictJSONField(default={})),
                ('shooting_stats', botdata.models.DefaultDictJSONField(default={})),
                ('stored_achievements', botdata.models.DefaultDictJSONField(default={})),
                ('experience', models.BigIntegerField(default=0)),
                ('spent_experience', models.BigIntegerField(default=0)),
                ('givebacks', models.IntegerField(default=0)),
                ('found_items', botdata.models.DefaultDictJSONField(default={})),
                ('bought_items', botdata.models.DefaultDictJSONField(default={})),
                ('bullets', models.IntegerField(default=6)),
                ('magazines', models.IntegerField(default=2)),
                ('last_giveback', models.DateTimeField(auto_now_add=True)),
                ('best_times', botdata.models.DefaultDictJSONField(default={})),
                ('killed', botdata.models.DefaultDictJSONField(default={})),
                ('hugged', botdata.models.DefaultDictJSONField(default={})),
                ('hurted', botdata.models.DefaultDictJSONField(default={})),
                ('resisted', botdata.models.DefaultDictJSONField(default={})),
                ('frightened', botdata.models.DefaultDictJSONField(default={})),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discordchannel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discordmember')),
                ('weapon_sabotaged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botdata.player')),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.RemoveField(
            model_name='channels',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='members',
            name='guild',
        ),
        migrations.RemoveField(
            model_name='members',
            name='user',
        ),
        migrations.RemoveField(
            model_name='players',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='players',
            name='member',
        ),
        migrations.RemoveField(
            model_name='players',
            name='weapon_sabotaged_by',
        ),
        migrations.DeleteModel(
            name='Aerich',
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
        migrations.DeleteModel(
            name='Guilds',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='discordmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discorduser'),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discordguild'),
        ),
    ]
