# Generated by Django 3.1.4 on 2020-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0004_auto_20201212_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='webhook_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='inventory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='trophys',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
