# Generated by Django 3.1.7 on 2021-03-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0004_remove_discorduser_times_ran_example_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='opened_support_tickets',
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botdata.discorduser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='botdata.discorduser')),
            ],
            options={
                'db_table': 'supportticket',
                'ordering': ['opened_at'],
            },
        ),
    ]
