# Generated by Django 3.1.4 on 2020-12-12 20:23

import botdata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0005_auto_20201212_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_powerups',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='best_times',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='bought_items',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='found_items',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='frightened',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='hugged',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='hurted',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='killed',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='resisted',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='shooting_stats',
            field=botdata.models.DefaultDictJSONField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='stored_achievements',
            field=botdata.models.DefaultDictJSONField(),
        ),
    ]
