# Generated by Django 3.1.7 on 2021-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0005_auto_20210329_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='close_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
