# Generated by Django 3.1.4 on 2020-12-13 13:30

import botdata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0007_auto_20201213_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='stored_achievements',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
    ]
