# Generated by Django 3.2 on 2021-04-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0008_auto_20210413_1923'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('member', 'channel')},
        ),
    ]
