# Generated by Django 3.1.4 on 2020-12-14 08:56

import botdata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0008_auto_20201213_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='best_times',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='frightened',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hugged',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='hurted',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='killed',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='resisted',
            field=botdata.models.DefaultDictJSONField(blank=True),
        ),
    ]
