# Generated by Django 3.2 on 2021-04-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0009_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('member', 'channel'), name='a_member_per_channel_only'),
        ),
    ]
