# Generated by Django 3.2.2 on 2021-05-07 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20210413_1923'),
        ('botdata', '0010_auto_20210414_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='last_tag_used',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tags.tag'),
        ),
    ]
