# Generated by Django 3.2.3 on 2021-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0011_supportticket_last_tag_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='levels_to_roles_ids_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
