# Generated by Django 3.1.4 on 2021-01-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0011_auto_20210101_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
