# Generated by Django 3.2.3 on 2021-05-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0012_discordchannel_levels_to_roles_ids_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='prestige_to_roles_ids_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
