# Generated by Django 3.1.4 on 2021-01-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0014_auto_20210105_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='botdata.discordguild'),
        ),
        migrations.AlterField(
            model_name='discordmember',
            name='guild',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botdata.discordguild'),
        ),
        migrations.AlterField(
            model_name='discordmember',
            name='user',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botdata.discorduser'),
        ),
        migrations.AlterField(
            model_name='player',
            name='member',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='botdata.discordmember'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weapon_sabotaged_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='botdata.player'),
        ),
    ]
