# Generated by Django 3.1.4 on 2021-01-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0015_auto_20210105_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='botdata.discordguild'),
        ),
        migrations.AlterField(
            model_name='discordmember',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botdata.discordguild'),
        ),
        migrations.AlterField(
            model_name='discordmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='botdata.discorduser'),
        ),
        migrations.AlterField(
            model_name='player',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botdata.discordmember'),
        ),
    ]
