# Generated by Django 3.2.4 on 2021-06-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0016_discordchannel_anti_trigger_wording'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event2021UserData',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='event2021data', serialize=False, to='botdata.discorduser')),
                ('first_played', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now_add=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('words_sent', models.IntegerField(default=0)),
                ('points_recovered', models.IntegerField(default=0)),
                ('points_acquired', models.IntegerField(default=0)),
                ('points_current', models.IntegerField(default=0)),
                ('points_exploded', models.IntegerField(default=0)),
                ('points_spent', models.IntegerField(default=0)),
                ('landmines_in_inventory', models.IntegerField(default=0)),
                ('safes_in_inventory', models.IntegerField(default=0)),
                ('electricity_in_inventory', models.IntegerField(default=0)),
                ('defuse_kits_bought', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'event2021userdata',
            },
        ),
        migrations.CreateModel(
            name='Event2021Landmines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('exploded', models.IntegerField(blank=True, null=True)),
                ('tripped', models.BooleanField(default=False)),
                ('disarmed', models.BooleanField(default=False)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmines_bought', to='botdata.event2021userdata')),
                ('stopped_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmines_stopped', to='botdata.event2021userdata')),
            ],
            options={
                'db_table': 'event2021landmines',
            },
        ),
    ]
