# Generated by Django 3.1.5 on 2021-02-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0016_auto_20210105_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
