# Generated by Django 3.2.4 on 2021-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0017_event2021landmines_event2021userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2021userdata',
            name='points_won',
            field=models.IntegerField(default=0),
        ),
    ]
