# Generated by Django 3.1.5 on 2021-02-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0017_discorduser_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='boss_kills',
            field=models.IntegerField(default=0),
        ),
    ]
