# Generated by Django 3.1.6 on 2021-02-14 17:19

import botdata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0018_discorduser_boss_kills'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='last_votes',
            field=botdata.models.DefaultDictJSONField(default={}),
            preserve_default=False,
        )
    ]
