# Generated by Django 3.2.4 on 2021-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0018_event2021userdata_points_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='event2021landmines',
            name='message',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
