# Generated by Django 3.1.6 on 2021-02-14 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0019_auto_20210214_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='votes',
        ),
    ]
