# Generated by Django 3.1.6 on 2021-02-14 17:20

import botdata.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0020_remove_discorduser_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='votes',
            field=botdata.models.DefaultDictJSONField(default={}),
            preserve_default=False,
        ),
    ]
