# Generated by Django 3.1.6 on 2021-02-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0021_discorduser_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='last_votes',
        ),
        migrations.RemoveField(
            model_name='discorduser',
            name='votes',
        ),
    ]
