# Generated by Django 3.1.6 on 2021-02-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0023_botlist_vote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botlist',
            table='botlist',
        ),
        migrations.AlterModelTable(
            name='vote',
            table='vote',
        ),
    ]
