# Generated by Django 3.2.5 on 2021-07-31 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0023_auto_20210731_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='landminesuserdata',
            name='member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landmines_data', to='botdata.discordmember'),
        ),
    ]
