# Generated by Django 3.1.6 on 2021-02-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0024_auto_20210214_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlist',
            name='webhook_handler',
            field=models.CharField(choices=[('generic', 'generic'), ('top.gg', 'top.gg'), ('None', 'None')], default='generic', help_text="What is the function that'll receive the request from the vote hooks", max_length=20),
        ),
    ]
