# Generated by Django 3.2.5 on 2021-07-31 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0025_auto_20210731_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landminesuserdata',
            name='user',
        ),

        migrations.AlterField(
            model_name='landminesuserdata',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='landmines_data', serialize=False, to='botdata.discordmember'),
        ),
    ]
