# Generated by Django 3.1.6 on 2021-02-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0025_auto_20210214_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlist',
            name='bot_certified',
            field=models.BooleanField(default=False, help_text='Whether the bot was certified on that bot list'),
        ),
        migrations.AddField(
            model_name='botlist',
            name='embed_code',
            field=models.TextField(blank=True, help_text="Code to show this bot list embed. This HTML won't be escaped."),
        ),
        migrations.AddField(
            model_name='botlist',
            name='notes',
            field=models.TextField(blank=True, help_text='Informations about this bot list'),
        ),
    ]
