# Generated by Django 3.2.5 on 2021-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0026_auto_20210731_1400'),
    ]

    operations = [
    ]
