# Generated by Django 3.1.6 on 2021-02-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0026_auto_20210215_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botlist',
            name='post_stats_method',
            field=models.CharField(choices=[('POST', 'POST'), ('PATCH', 'PATCH'), ('None', 'None')], default='POST', help_text='What HTTP method should be used to send the stats', max_length=10),
        ),
    ]
