# Generated by Django 3.2.5 on 2021-07-31 14:38

from django.db import migrations


def move_primary_keys_from_user_to_member_on_landmines(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    LandminesUserData = apps.get_model('botdata', 'LandminesUserData')
    LandminesPlaced = apps.get_model('botdata', 'LandminesPlaced')
    DiscordMember = apps.get_model('botdata', 'DiscordMember')
    DiscordGuild = apps.get_model('botdata', 'DiscordGuild')

    dh_guild = DiscordGuild.objects.get(discord_id=195260081036591104)

    for landmine in LandminesPlaced.objects.all():
        placed_by_user_id = landmine.placed_by_id
        placed_by_member, _ = DiscordMember.objects.all().get_or_create(user=placed_by_user_id, guild=dh_guild)
        placed_by_userdata, _ = LandminesUserData.objects.all().get_or_create(member=placed_by_member)
        landmine.placed_by = placed_by_userdata

        stopped_by_user_id = landmine.stopped_by_id
        if stopped_by_user_id:
            stopped_by_member, _ = DiscordMember.objects.all().get_or_create(user=stopped_by_user_id, guild=dh_guild)
            stopped_by_userdata, _ = LandminesUserData.objects.all().get_or_create(member=stopped_by_member)

            landmine.stopped_by = stopped_by_userdata

        landmine.save()


def reset_pks_to_user(apps, schema_editor):
    LandminesPlaced = apps.get_model('botdata', 'LandminesPlaced')

    for landmine in LandminesPlaced.objects.all():
        placed_by_member = landmine.placed_by.member
        landmine.placed_by_id = placed_by_member.user.id

        stopped_by = landmine.stopped_by
        if stopped_by:
            landmine.stopped_by_id = stopped_by.member.user.id

        landmine.save()


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0027_auto_20210731_1419'),
    ]

    operations = [
        migrations.RunPython(move_primary_keys_from_user_to_member_on_landmines, reset_pks_to_user)
    ]
