# Generated by Django 3.1.6 on 2021-02-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0027_auto_20210215_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='botlist',
            name='bot_verified',
            field=models.BooleanField(default=False, help_text='Whether the bot was verified by the bot list staff'),
        ),
    ]
