# Generated by Django 3.1.6 on 2021-02-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0028_botlist_bot_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordguild',
            name='channel_disabled_message',
            field=models.BooleanField(default=True),
        ),
    ]
