# Generated by Django 3.2.5 on 2021-07-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0028_auto_20210731_1438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landminesplaced',
            table='landmines_placed',
        ),
    ]
