# Generated by Django 3.2.5 on 2021-07-31 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0029_alter_landminesplaced_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landminesuserdata',
            table='landmines_userdata',
        ),
    ]
