# Generated by Django 3.2.5 on 2021-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0030_alter_landminesuserdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='landmines_commands_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discordchannel',
            name='landmines_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
