# Generated by Django 3.2.5 on 2021-08-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0031_auto_20210731_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='landminesuserdata',
            name='id',
            field=models.BigIntegerField(null=True),
        ),
    ]
