# Generated by Django 3.2.5 on 2021-08-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0032_landminesuserdata_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landminesuserdata',
            name='id',
        ),
    ]
