# Generated by Django 3.2.5 on 2021-08-08 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0033_remove_landminesuserdata_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='landminesuserdata',
            table='landmines_old_userdata',
        ),
    ]
