# Generated by Django 3.2.5 on 2021-08-08 17:06

from django.db import migrations


def move_landmines_old_to_new(apps, schema_editor):
    OldLandminesUserData = apps.get_model('botdata', 'LandminesUserData')
    NewLandminesUserData = apps.get_model('botdata', 'NewLandminesUserData')

    NewLandminesUserData.objects.all().delete()

    for mine in OldLandminesUserData.objects.all().values():
        NewLandminesUserData.objects.create(**mine)


def move_landmines_new_to_old(apps, schema_editor):
    OldLandminesUserData = apps.get_model('botdata', 'LandminesUserData')
    NewLandminesUserData = apps.get_model('botdata', 'NewLandminesUserData')

    OldLandminesUserData.objects.all().delete()

    for mine in NewLandminesUserData.objects.all().values():
        OldLandminesUserData.objects.create(**mine)


class Migration(migrations.Migration):
    dependencies = [
        ('botdata', '0035_newlandminesuserdata'),
    ]

    operations = [
        migrations.RunPython(move_landmines_old_to_new, move_landmines_new_to_old)
    ]
