# Generated by Django 3.2.5 on 2021-08-08 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0036_auto_20210808_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landminesplaced',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmines_bought', to='botdata.newlandminesuserdata'),
        ),
        migrations.AlterField(
            model_name='landminesplaced',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landmines_stopped', to='botdata.newlandminesuserdata'),
        ),
        migrations.DeleteModel(
            name='LandminesUserData',
        ),
    ]
