# Generated by Django 3.2.5 on 2021-08-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0037_auto_20210808_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewLandminesUserData',
            new_name='LandminesUserData',
        ),
    ]
