# Generated by Django 3.2.5 on 2021-08-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0039_auto_20210808_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landminesuserdata',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landmines_data', to='botdata.discordmember'),
        ),
    ]
