# Generated by Django 3.2.6 on 2021-08-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0040_alter_landminesuserdata_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandminesProtects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed', models.DateTimeField(auto_now_add=True)),
                ('word', models.CharField(max_length=50)),
                ('message', models.CharField(blank=True, default='', max_length=2000)),
                ('protected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_protected', to='botdata.landminesuserdata')),
            ],
            options={
                'db_table': 'landmines_protected',
            },
        ),
    ]
