# Generated by Django 3.2.6 on 2021-08-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0041_landminesprotects'),
    ]

    operations = [
        migrations.AddField(
            model_name='landminesuserdata',
            name='shields_bought',
            field=models.IntegerField(default=0),
        ),
    ]
