# Generated by Django 3.2.6 on 2021-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0042_landminesuserdata_shields_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='landminesprotects',
            name='protect_count',
            field=models.IntegerField(default=0),
        ),
    ]
