# Generated by Django 3.2.6 on 2021-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0043_landminesprotects_protect_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('measure_interval', models.IntegerField()),
                ('ws_send', models.IntegerField()),
                ('ws_recv', models.IntegerField()),
                ('messages', models.IntegerField()),
                ('commands', models.IntegerField()),
                ('command_errors', models.IntegerField()),
                ('command_completions', models.IntegerField()),
                ('guilds', models.IntegerField()),
                ('users', models.IntegerField()),
                ('shards', models.IntegerField()),
                ('ready', models.BooleanField()),
                ('ws_ratelimited', models.BooleanField()),
                ('ws_latency', models.FloatField()),
            ],
            options={
                'db_table': 'botstate',
            },
        ),
    ]
