# Generated by Django 4.0.6 on 2022-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botdata', '0044_botstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordchannel',
            name='spawn_weight_cartographer_ducks',
            field=models.SmallIntegerField(default=3),
        ),
    ]
