# Generated by Django 4.2.8 on 2023-12-27 19:39

import botdata.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("botdata", "0045_discordchannel_spawn_weight_cartographer_ducks"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="ducks_killed_today",
            field=botdata.models.DefaultDictJSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="ducks_killed_today_last_reset",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
