# Generated by Django 4.2.8 on 2024-01-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("botdata", "0046_player_ducks_killed_today_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discordguild",
            name="language",
            field=models.CharField(default="en", max_length=8),
        ),
    ]
