# Generated by Django 5.1.6 on 2025-02-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("botdata", "0047_alter_discordguild_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="painted_dry_wall_left",
            field=models.IntegerField(default=0),
        ),
    ]
