# Generated by Django 3.1.4 on 2021-01-01 18:20

from django.db import migrations


def set_site_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Site = apps.get_model('sites', 'Site')
    site = Site.objects.first()
    site.domain = "duckhunt.me"
    site.name = "DuckHunt Discord"
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ('sites', '0002_alter_domain_unique')
    ]

    operations = [
        migrations.RunPython(set_site_data, migrations.RunPython.noop),
    ]
